# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shifouchoucha',
            field=models.CharField(choices=[('是', '是'), ('否', '否')], default='是', max_length=10, null=True, verbose_name='是否抽查'),
        ),
    ]
