# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_shifouchoucha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='People',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
